version: '3.1'
services:
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PW}
    ports:
      - '27017:27017'
    volumes:
      - /data:/data/db #this makes it persistant even when container is down

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PW}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PW}@mongo:27017/